# MAIN MENUS
main:
  # HOME
  - name: Home
    identifier: menu.home
    url:
    weight: 1

  # PRODUCTS MENU
  - name: Products
    identifier: menu.products
    url: /img/template-easy-customize.png
    weight: 2

  # PRODUCTS MENU - PERIPHERALS SECTION
  - name: Peripherals
    identifier: section.peripherals
    url:
    weight: 1
    parent: menu.products
    post: 1

  - name: Mice
    identifier: products.mice
    url:
    weight: 1
    parent: section.peripherals

  - name: Keyboards
    identifier: products.keyboards
    url:
    weight: 2
    parent: section.peripherals

  - name: Headphones
    identifier: products.headphones
    url:
    weight: 3
    parent: section.peripherals

  # PRODUCTS MENU - PHONE ACCESSORIES SECTION
  - name: Phone Accessories
    identifier: section.phone-accessories
    url:
    weight: 3
    parent: menu.products
    post: 2

  - name: Earphones
    identifier: phone-accessories.earphones
    url:
    weight: 1
    parent: section.phone-accessories

  - name: Cables
    identifier: phone-accessories.cables
    url:
    weight: 2
    parent: section.phone-accessories

  # PRODUCTS MENU - BATTERIES SECTION
  - name: Batteries
    identifier: section.batteries
    url:
    weight: 2
    parent: menu.products
    post: 1

  - name: Power banks
    identifier: batteries.power-banks
    url:
    weight: 1
    parent: section.batteries

  # PRODUCTS MENU - SPEAKERS SECTION
  - name: Speakers
    identifier: section.speakers
    url:
    weight: 4
    parent: menu.products
    post: 2

  - name: Speakers
    identifier: speakers.speakers
    url:
    weight: 1
    parent: section.speakers

  - name: Microphones
    identifier: speakers.microphones
    url:
    weight: 2
    parent: section.speakers

  # BLOG
  - name: Blog
    identifier: menu.blog
    url: blog
    weight: 5

  # About
  - name: About us
    identifier: menu.about
    url: about
    weight: 6

  # CONTACT
  - name: Contact
    identifier: menu.contact
    url: contact
    weight: 7

topbar:
  - weight: 1
    name: Whatsapp
    url: https://wa.me/573128459082
    pre: <i class='fab fa-2x fa-whatsapp'></i>
  - weight: 2
    name: Facebook
    url: https://facebook.com/skypluscolombia
    pre: <i class='fab fa-2x fa-facebook'></i>
  - weight: 3
    name: Instagram
    url: https://instagram.com/skypluscolombia
    pre: <i class='fab fa-2x fa-instagram'></i>
