# Main menu
main:
  - name: Home
    identifier: menu.home
    url: /
    weight: 1

  - name: Products
    identifier: menu.products
    url: /img/template-easy-customize.png
    weight: 3

  - name: Shortcodes
    identifier: section.shortcodes
    url: ""
    weight: 1
    parent: menu.products
    post: 1

  - name: Header variations
    identifier: section.headervariations
    url: ""
    weight: 2
    parent: menu.products
    post: 2

  - name: Accordions
    url: ""
    weight: 1
    parent: section.shortcodes

  - name: Alerts
    url: ""
    weight: 2
    parent: section.shortcodes

  - name: Buttons
    url: ""
    weight: 3
    parent: section.shortcodes

  - name: Content Boxes
    url: ""
    weight: 4
    parent: section.shortcodes

  - name: Horizontal Blocks
    url: ""
    weight: 5
    parent: section.shortcodes

  - name: Pagination
    url: ""
    weight: 6
    parent: section.shortcodes

  - name: Tabs
    url: ""
    weight: 7
    parent: section.shortcodes

  - name: Typography
    url: ""
    weight: 8
    parent: section.shortcodes

  - name: Default Sticky Header
    url: ""
    weight: 1
    parent: section.headervariations

  - name: No Sticky Header
    url: ""
    weight: 2
    parent: section.headervariations

  - name: Light Header
    url: ""
    weight: 3
    parent: section.headervariations

  - name: Portfolio
    identifier: menu.portfolio
    url: /img/template-homepage.png
    weight: 3

  - name: Portfolio
    identifier: section.portfolio
    url: ""
    weight: 1
    parent: menu.portfolio
    post: 1

  - name: 2 Columns
    url: ""
    weight: 1
    parent: section.portfolio

  - name: 2 Columns With Negative Space
    url: ""
    weight: 2
    parent: section.portfolio

  - name: 3 Columns
    url: ""
    weight: 3
    parent: section.portfolio

  - name: 3 Columns With Negative Space
    url: ""
    weight: 4
    parent: section.portfolio

  - name: 4 Columns
    url: ""
    weight: 5
    parent: section.portfolio

  - name: 4 Columns With Negative Space
    url: ""
    weight: 6
    parent: section.portfolio

  - name: Portfolio - detail
    url: ""
    weight: 7
    parent: section.portfolio

  - name: Portfolio - detail 2
    url: ""
    weight: 8
    parent: section.portfolio

  - name: About
    identifier: section.about
    url: ""
    weight: 2
    parent: menu.portfolio
    post: 2

  - name: About Us
    identifier: item.about-us
    url: /about
    weight: 1
    parent: section.about

  - name: Our Team
    url: ""
    weight: 2
    parent: section.about

  - name: Marketing
    identifier: section.marketing
    url: ""
    weight: 3
    parent: menu.portfolio
    post: 2

  - name: Packages
    url: ""
    weight: 1
    parent: section.marketing

  - name: All Pages
    identifier: menu.allpages
    url: ""
    weight: 4

  - name: Home
    identifier: section.ap-home
    url: ""
    weight: 1
    parent: menu.allpages
    post: 1

  - name: About
    identifier: section.ap-about
    url: ""
    weight: 2
    parent: menu.allpages
    post: 1

  - name: Marketing
    identifier: section.ap-marketing
    url: ""
    weight: 3
    parent: menu.allpages
    post: 1

  - name: Portfolio
    identifier: section.ap-portfolio
    url: ""
    weight: 1
    parent: menu.allpages
    post: 2

  - name: User Pages
    identifier: section.ap-userpages
    url: ""
    weight: 2
    parent: menu.allpages
    post: 2

  - name: Shop
    identifier: section.ap-shop
    url: ""
    weight: 1
    parent: menu.allpages
    post: 3

  - name: Shop - Order Process
    identifier: section.ap-shoporderprocess
    url: ""
    weight: 2
    parent: menu.allpages
    post: 3

  - name: Contact
    identifier: section.ap-contact
    url: ""
    weight: 1
    parent: menu.allpages
    post: 4

  - name: Pages
    identifier: section.ap-pages
    url: ""
    weight: 2
    parent: menu.allpages
    post: 4

  - name: Blog
    identifier: section.ap-blog
    url: /blog/
    weight: 3
    parent: menu.allpages
    post: 4

  - name: Blog Listing Big
    url: /blog/
    weight: 1
    parent: section.ap-blog

  - name: Blog
    identifier: menu.blog
    url: /blog/
    weight: 5

  - name: FAQ
    identifier: menu.faq
    url: /faq/
    weight: 6

  - name: Contact
    identifier: contact
    url: /contact/
    weight: 7

topbar:
  - weight: 1
    name: Whatsapp
    url: https://wa.me/573128459082
    pre: <i class='fab fa-2x fa-whatsapp'></i>
  - weight: 2
    name: Facebook
    url: https://facebook.com/skypluscolombia
    pre: <i class='fab fa-2x fa-facebook'></i>
  - weight: 3
    name: Instagram
    url: https://instagram.com/skypluscolombia
    pre: <i class='fab fa-2x fa-instagram'></i>
